apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: dev
spec:
  kafka:
    version: 3.3.1
    replicas: 3
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    resources: 
      requests:
        memory: 250Mi
        cpu: "500m"
      limits:
        memory: 1Gi
        cpu: "1"
    readinessProbe: 
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions: 
      -Xms: 1024m
      -Xmx: 1024m
    # Port number used by the listener inside Kafka. The port number has to be unique within a given Kafka cluster. Allowed port numbers are 9092 and higher with the exception of ports 9404 and 9999, which are already used for Prometheus and JMX. Depending on the listener type, the port number might not be the same as the port number that connects Kafka clients.
    listeners:
            ##      - name: external
            ##        port: 9094
            ##        type: ingress
            ##        tls: false
        # authentication:
        #   type: tls
        ##        configuration:
        ##          bootstrap:
        ##            host: kafka.cch.com
          # brokers:
          # - broker: 0
          #   host: broker-0.myingress.com
          # - broker: 1
          #   host: broker-1.myingress.com
          # - broker: 2
          #   host: broker-2.myingress.com
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.3"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    resources:
      requests:
        memory: 512Mi
        cpu: "500M"
      limits:
        memory: 1Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      watchedNamespace: dev
      reconciliationIntervalSeconds: 60
      logging: 
        type: inline
        loggers:
          rootLogger.level: "INFO"
      resources:
        requests:
          memory: 512Mi
          cpu: "250M"
        limits:
          memory: 512Mi
          cpu: "500M"
    userOperator: {}
