apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-consumer
data:
  application.properties: |
    mp.messaging.incoming.played-vehicles.topic=vehicle
    mp.messaging.incoming.played-vehicles.auto.offset.reset=earliest
    mp.messaging.incoming.played-vehicles.connector=smallrye-kafka
    mp.messaging.incoming.played-vehicles.broadcast=true
    mp.messaging.incoming.brands.topic=brand
    mp.messaging.incoming.brands.auto.offset.reset=earliest
    mp.messaging.incoming.brands.connector=smallrye-kafka
    mp.messaging.incoming.played-vehicles.value.deserializer=org.cch.deserializer.VehicleDeserializer
    kafka-bootstrap.servers=my-cluster-kafka-bootstrap.dev.svc.cluster.local:9092
    quarkus.mongodb.connection-string=mongodb://vehicle-user:a123456789@vehicle-mongodb-0.vehicle-mongodb-svc.mongodb.svc.cluster.local:27017/vehicle?replicaSet=vehicle-mongodb&ssl=false&authSource=vehicle