apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    mp.messaging.incoming.played-vehicles.topic=vehicle
    mp.messaging.incoming.played-vehicles.auto.offset.reset=earliest
    mp.messaging.incoming.played-vehicles.connector=smallrye-kafka
    mp.messaging.incoming.brands.topic=brand
    mp.messaging.incoming.brands.auto.offset.reset=earliest
    mp.messaging.incoming.brands.connector=smallrye-kafka
    kafka-bootstrap.servers=my-cluster-kafka-bootstrap.dev.svc.cluster.local:9092