apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer-partition
  name: kafka-producer-partition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-partition
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-producer-partition
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - image: cch0124/kafka-produce-partition:1.0.0-SNAPSHOT
          name: kafka-producer-partition
          imagePullPolicy: Always # IfNotPresent
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          env:
            - name: kafka.partition.number
              value: "1"
            - name: kafka.topic
              value: event
            - name: kafka.brokers.host
              value: my-cluster-kafka-bootstrap.default.svc.cluster.local:9092
            - name: kafka.time.period
              value: "1000"
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
      restartPolicy: Always