image:
  tag: "v2.2.9"
  pullPolicy: "Always"

ingress:
  enabled: true

autoscaling:
  enabled: true

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - appName
          topologyKey: topology.kubernetes.io/zone
app:
  # -- Application defined properties.
  properties:
    a=b