apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-my-collector
  namespace: observability
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
                  #            endpoint: otel-my-collector-collector.observability.svc.cluster.local:4317
          http:
    exporters:
            #      prometheus:
            #        endpoint: http://prometheus-stack-kube-prom-prometheus:9090
      logging:
        loglevel: debug
      otlp:
        endpoint: tempo-distributor.observability.svc.cluster.local:4317
        tls:
          insecure: true
      loki:
        endpoint: http://loki-loki-distributed-gateway.observability.svc.cluster.local:3100/loki/api/v1/push
        tls:
          insecure: true

    processors:
      attributes:
        actions:
        - action: insert
          key: loki.attribute.labels
          value: http_status_code
        - action: insert
          key: http_status_code
          value: 500
    
      resource:
        attributes:
        - action: insert
          key: loki.resource.labels
          value: host_name, pod_name
        - action: insert
          key: host_name
          value: guarana
        - action: insert
          key: pod_name
          value: guarana-pod-01
    
    extensions:
    
    service:
      extensions:
      pipelines:
              #        metrics:
              #          receivers: [otlp]
              #          exporters: [logging, prometheus]
        traces:
          receivers: [otlp]
          exporters: [logging, otlp]
        logs:
          receivers: [otlp]
          processors: [resource, attributes]
          exporters: [logging, loki]
