apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-my-collector
  namespace: observability
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
                  #            endpoint: otel-my-collector-collector.observability.svc.cluster.local:4317
          http:
    exporters:
            #      prometheus:
            #        endpoint: http://prometheus-stack-kube-prom-prometheus:9090
      logging:
        loglevel: debug
      otlp:
        endpoint: tempo-distributor.observability.svc.cluster.local:4317
        tls:
          insecure: true
      loki:
        endpoint: http://loki-loki-distributed-distributor.observability.svc.cluster.local:3100/loki/api/v1/push
        tls:
          insecure: true

    processors:
      attributes:
        actions:
        - action: insert
          key: event_domain
          from_attribute: event.domain
        - action: insert
          key: loki.attribute.labels
          value: event_domain

      resource:
        attributes:
        - action: insert
          key: service_name
          from_attribute: service.name
        - action: insert
          key: service_namespace
          from_attribute: service.namespace
        - action: insert
          key: loki.resource.labels
          value: service_name, service_namespace

    
    extensions:
    
    service:
      extensions:
      pipelines:
              #        metrics:
              #          receivers: [otlp]
              #          exporters: [logging, prometheus]
        traces:
          receivers: [otlp]
          exporters: [logging, otlp]
        logs:
          receivers: [otlp]
          processors: [resource, attributes]
          exporters: [logging, loki]
