version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - app
  movie-app:
    image: cch0124/cdc-camel:051b7d0-dev
    ports:
     - 8080:8080
    environment:
     - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://172.17.35.84:5432/test
     - QUARKUS_DATASOURCE_DB_KIND=postgresql
     - QUARKUS_DATASOURCE_USERNAME=itachi
     - QUARKUS_DATASOURCE_PASSWORD=123456
     - PG_DATABASE_HOSTNAME=172.17.35.84
     - PG_DATABASE_PORT=5432
     - PG_DATABASE_NAME=test
     - PG_DATABASE_SCHEMA=public
     - PG_DATABASE_TABLES=pubic.movie
    depends_on:
      - postgres
    networks:
      - app

networks:
  app: