version: '3.9'

services:
  mongo:
    image: mongo:6.0.2
    hostname: mongodb
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./script/init.js:/scripts/init.js
      - mongo_data:/data/db
    networks:
      - mongo-network
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongosh -u test -p test123 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: ["--replSet", "dbrs", "--bind_ip_all"]

networks:
  mongo-network:
    driver: bridge
volumes:
  mongo_data:
