apiVersion: apps.emqx.io/v1beta3
kind: EmqxPlugin
metadata:
  name: emqx-web-hook
  namespace: dev
  annotations:
    url: "https://github.com/emqx/emqx/blob/v4.4.10/apps/emqx_web_hook/etc/emqx_web_hook.conf"
spec:
  selector:
    "apps.emqx.io/instance": "emqx"
    "env": "prod"
  pluginName: emqx_web_hook
  config:
    "web.hook.url": "https://wiclouddev.biotrd.net/log-service/emqx/webhook/logging"
    "web.hook.headers.content-type": "application/json"
    "web.hook.body.encoding_of_payload_field": "plain"
    "web.hook.rule.client.connect.1" : '{"action": "on_client_connect"}'
    "web.hook.rule.client.connack.1" : '{"action": "on_client_connack"}'
    "web.hook.rule.client.connected.1" : '{"action": "on_client_connected"}'
    "web.hook.rule.client.disconnected.1": '{"action": "on_client_disconnected"}'
    "web.hook.rule.client.subscribe.1" : '{"action": "on_client_subscribe"}'
    "web.hook.rule.client.unsubscribe.1" : '{"action": "on_client_unsubscribe"}'
    "web.hook.rule.session.subscribed.1" : '{"action": "on_session_subscribed"}'
    "web.hook.rule.session.unsubscribed.1": '{"action": "on_session_unsubscribed"}'
    "web.hook.rule.session.terminated.1" : '{"action": "on_session_terminated"}'
    "web.hook.rule.message.publish.1" : '{"action": "on_message_publish"}'
    "web.hook.rule.message.delivered.1" : '{"action": "on_message_delivered"}'
    "web.hook.rule.message.acked.1" : '{"action": "on_message_acked"}'
    #    "web.hook.encode_payload": "base64"
