apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    mp.messaging.outgoing.brand.topic=brand
    mp.messaging.outgoing.vehicle.topic=vehicle
    kafka.bootstrap.servers=my-cluster-kafka-bootstrap.dev.svc.cluster.local:9092
    mp.messaging.outgoing.brand.connector=smallrye-kafka
    mp.messaging.outgoing.vehicle.connector=smallrye-kafka
    mp.messaging.outgoing.brand.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
    mp.messaging.outgoing.vehicle.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer