apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer-partition
  name: kafka-consumer-partition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer-partition
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-consumer-partition
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - image: cch0124/kafka-consumer-partition:1.0.0-SNAPSHOT
          name: kafka-consumer-partition
          imagePullPolicy: Always # IfNotPresent
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          env:
            - name: kafka.topics
              value: event,order
            - name: kafka.brokers
              value: my-cluster-kafka-bootstrap.default.svc.cluster.local:9092
            - name: kafka.groupId
              value: event
            - name: kafka.partition
              value: "1"
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
      restartPolicy: Always