version: '3.9'

services:
  mongo:
    image: mongo:6.0.2
    hostname: mongodb
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root@1234
      MONGO_INITDB_DATABASE: "vehicle"
    ports:
      - 27017:27017
    volumes:
      - ./script/:/docker-entrypoint-initdb.d/:ro
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
